# Generated by Django 4.1.8 on 2023-04-27 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=255, verbose_name="Subject of the ticket"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Content")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("type", "Type"),
                            ("status", "Status"),
                            ("priority", "Priority"),
                        ],
                        max_length=8,
                        verbose_name="Category of the label",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="unspecified",
                        max_length=20,
                        unique=True,
                        verbose_name="Name of the label",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        default="grey", max_length=20, verbose_name="Associated colour"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labels",
                        to="tickets.ticket",
                    ),
                ),
            ],
        ),
    ]
