# Generated by Django 4.1.8 on 2023-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_label_category_alter_label_colour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="colour",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("yellow", "Yellow"),
                    ("grey", "Grey"),
                    ("purple", "Purple"),
                ],
                default="grey",
                max_length=10,
                verbose_name="Associated colour",
            ),
        ),
    ]
