# Generated by Django 4.1.8 on 2023-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_alter_label_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="slug",
            field=models.SlugField(default="slug", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="slug",
            field=models.SlugField(default="slug", unique=True),
            preserve_default=False,
        ),
    ]
