# Generated by Django 4.1.8 on 2023-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_label_slug_ticket_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(
                help_text="Enter the name of the label",
                max_length=20,
                unique=True,
                verbose_name="Name of the label",
            ),
        ),
    ]
