# Generated by Django 4.1.8 on 2023-05-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_label_slug_ticket_slug_squashed_0005_alter_label_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="ticket",
        ),
        migrations.AddField(
            model_name="label",
            name="ticket",
            field=models.ManyToManyField(related_name="labels", to="tickets.ticket"),
        ),
    ]
